name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
    - name: testNoError
      id: testnoerror
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: testNoError
        setup-command: ''
        command: sudo locale-gen ja_JP.UTF-8 && export LANG=ja_JP.UTF-8 && sudo update-locale
          && gradle test --tests "ProgE1Test.testNoError"
        timeout: 10
        max-score: 4
    - name: testStdOutWithError
      id: teststdoutwitherror
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: testStdOutWithError
        setup-command: ''
        command: sudo locale-gen ja_JP.UTF-8 && export LANG=ja_JP.UTF-8 && sudo update-locale
          && gradle test --tests "ProgE1Test.testStdOutWithError"
        timeout: 10
        max-score: 4
    - name: testStdErrWithError1
      id: teststderrwitherror1
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: testStdErrWithError1
        setup-command: ''
        command: sudo locale-gen ja_JP.UTF-8 && export LANG=ja_JP.UTF-8 && sudo update-locale
          && gradle test --tests "ProgE1Test.testStdErrWithError1"
        timeout: 10
        max-score: 4
    - name: testStdErrWithError2
      id: teststderrwitherror2
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: testStdErrWithError2
        setup-command: ''
        command: sudo locale-gen ja_JP.UTF-8 && export LANG=ja_JP.UTF-8 && sudo update-locale
          && gradle test --tests "ProgE1Test.testStdErrWithError2"
        timeout: 10
        max-score: 4
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TESTNOERROR_RESULTS: "${{steps.testnoerror.outputs.result}}"
        TESTSTDOUTWITHERROR_RESULTS: "${{steps.teststdoutwitherror.outputs.result}}"
        TESTSTDERRWITHERROR1_RESULTS: "${{steps.teststderrwitherror1.outputs.result}}"
        TESTSTDERRWITHERROR2_RESULTS: "${{steps.teststderrwitherror2.outputs.result}}"
      with:
        runners: testnoerror,teststdoutwitherror,teststderrwitherror1,teststderrwitherror2
